#!/usr/bin/env node
/**
 * GEMINI.md is the five SKILL.md bodies in one file, because the Gemini CLI
 * loads a single context file per extension rather than a skills directory.
 * The skills stay the source; this only concatenates them, so there is one
 * place to edit a workflow. `--check` exits 1 when the file has drifted.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const skillsDir = join(root, "skills");
const target = join(root, "GEMINI.md");

const PREAMBLE = `<!-- Generated by scripts/build-context.mjs from skills/*/SKILL.md. Do not edit. -->

# wazap: WhatsApp for your agent

The \`whatsapp\` MCP server puts the user's own WhatsApp account behind a set of
tools. Call \`learn\` first: it returns every tool, the id formats, the workflows
and every error code with what to do about it.

The sections below are the workflows behind those tools. Each one says when it
applies, what to collect, and what to deliver.
`;

/** Body without frontmatter, every heading pushed one level down so the skill's own title lands at H2. */
function section(text) {
  const body = text.replace(/^---\n[\s\S]*?\n---\n/, "").trim();
  return body.replace(/^(#{1,5}) /gm, "#$1 ");
}

function render() {
  const dirs = readdirSync(skillsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const sections = dirs.map((dir) => section(readFileSync(join(skillsDir, dir, "SKILL.md"), "utf8")));
  return `${PREAMBLE}\n${sections.join("\n\n")}\n`;
}

const wanted = render();
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    /* absent counts as stale */
  }
  if (current === wanted) process.exit(0);
  console.error("GEMINI.md is out of date with skills/. Run `node scripts/build-context.mjs`.");
  process.exit(1);
}

writeFileSync(target, wanted);
console.log(`wrote GEMINI.md (${Buffer.byteLength(wanted)} bytes)`);
